on:
  push:
    paths:
        - 'dataset/**'
        - 'scripts/**'
        - 'source/**'
  pull_request:
    paths:
      - 'dataset/**'
      - 'scripts/**'
      - 'source/**'

name: Build 

jobs:
  build_and_test_windows:
      runs-on: windows-2022
      steps:
        - uses: actions/checkout@v4
        - name: Set up MSYS2
          uses: msys2/setup-msys2@v2
          with:
            msystem: MINGW64
            update: true
            install: >-
              make
              mingw-w64-x86_64-gcc
              file
        - name: Build trimal for Windows x86_64
          run: |
            cd source
            make -f makefile.Windows
            file trimal.exe
            file readal.exe
            file statal.exe
            cd ..
            bash scripts/generate_trimmed_msas_Windows.sh
            echo "test_msas/gappyout/example.004.AA.fasta"
            cat test_msas/gappyout/example.004.AA.fasta
            echo "dataset/trimmed_msas/gappyout/example.004.AA.fasta"
            cat dataset/trimmed_msas/gappyout/example.004.AA.fasta
            bash scripts/compare_trimmed_msas.sh
