on:
  push:
    paths:
        - 'dataset/**'
        - 'scripts/**'
        - 'source/**'
  pull_request:
    paths:
      - 'dataset/**'
      - 'scripts/**'
      - 'source/**'

name: Build 

jobs:
  build_and_test_windows:
      runs-on: windows-2022
      steps:
      - uses: actions/checkout@v4
      - name: Download Release Binaries
        run: |
          curl -L -o trimal.zip https://github.com/inab/trimal/releases/download/v1.5.0/trimAl_Windows_x86-64.zip

      - name: Unzip Binaries
        run: |
          powershell -Command "Expand-Archive -Path trimal.zip -DestinationPath ."
      - name: List Directory Contents
        run: |
          dir .\
          
      - name: Verify Binaries
        run: |
          # Use PowerShell or native Windows commands to verify binaries
          Get-Command .\trimal.exe
          
      - name: Run generate_trimmed_msas.ps1
        run: |
          powershell -ExecutionPolicy Bypass -File .\scripts\generate_trimmed_msas.ps1

      - name: Run compare_trimmed_msas.ps1
        run: |
          powershell -ExecutionPolicy Bypass -File .\scripts\compare_trimmed_msas.ps1
