on:
  push:
    paths:
        - 'dataset/**'
        - 'scripts/**'
        - 'source/**'
  pull_request:
    paths:
      - 'dataset/**'
      - 'scripts/**'
      - 'source/**'

name: Build 

jobs:
  build_and_test_windows:
      runs-on: windows-2022
      steps:
      #- uses: actions/checkout@v4
      - name: Download Release Binaries
        run: |
          curl -L -o trimal.zip https://github.com/inab/trimal/releases/download/v1.5.0/trimAl_Windows_x86-64.zip

      - name: Unzip Binaries
        run: |
          powershell -Command "Expand-Archive -Path trimal.zip -DestinationPath ."
      - name: List Directory Contents
        run: |
          dir .\
          dir .\trimAl_Windows_x86-64\
          
      - name: Verify Binaries
        run: |
          # Use PowerShell or native Windows commands to verify binaries
          Get-Command .\trimAl_Windows_x86-64\trimal.exe
          Get-Command .\trimAl_Windows_x86-64\readal.exe
          Get-Command .\trimAl_Windows_x86-64\statal.exe
          
      - name: Run Tests on Binaries
        run: |
          .\trimAl_Windows_x86-64\trimal.exe --help
