# Workflow to get data of paths and referrers traffic until enough days are saved to interpolate daily traffic
name: Temporal traffic workflow

on:
  schedule:
    - cron:  '31 9 * * *'

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: trimAl

      - name: Fetch paths data
        run: |
          paths_file="$GITHUB_WORKSPACE/traffic/paths.json"
          github_api_url="https://api.github.com/repos/${{ github.repository }}/traffic/popular/paths"
          github_token="${{ secrets.TRAFFIC_API }}"

          traffic_content=$(curl --request GET \
                             --url "$github_api_url" \
                             --header "X-GitHub-Api-Version:2022-11-28" \
                             --header "authorization: Bearer $github_token" \
                             --header 'content-type: application/json')
          
          echo "$traffic_content" > paths_traffic_response.json
          current_date=$(date +"%Y-%m-%d")
          jq --arg request_date "$current_date" '.[] |= . + {request_date: $request_date}' paths_traffic_response.json > temp_paths_traffic.json && rm paths_traffic_response.json
          cat temp_paths_traffic.json
          cat temp_views.json > "$paths_file" && rm temp_views.json temp_paths_traffic.json
          cat "$paths_file"
      - name: Fetch referrers data
        run: |
          referrers_file="$GITHUB_WORKSPACE/traffic/referrers.json"
          github_api_url="https://api.github.com/repos/${{ github.repository }}/traffic/popular/referrers"
          github_token="${{ secrets.TRAFFIC_API }}"

          traffic_content=$(curl --request GET \
                             --url "$github_api_url" \
                             --header "X-GitHub-Api-Version:2022-11-28" \
                             --header "authorization: Bearer $github_token" \
                             --header 'content-type: application/json')
          
          echo "$traffic_content" > referrers_traffic_response.json
          current_date=$(date +"%Y-%m-%d")
          jq --arg request_date "$current_date" '.[] |= . + {request_date: $request_date}' referrers_traffic_response.json > temp_referrers_traffic.json && rm referrers_traffic_response.json
          cat temp_referrers_traffic.json
          cat temp_views.json > "$referrers_file" && rm temp_views.json temp_referrers_traffic.json
          cat "$referrers_file"
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions bot
          author_email: ${{ vars.CI_EMAIL }}
          message: Update temporary traffic data
      - name: Create Pull Request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRAFFIC_API }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"title":"[DO NOT MERGE] Track temporary traffic for paths and referrers","head":"schedule-traffic-workflow","base":"trimAl"}'