name: Traffic workflow test

on: workflow_dispatch

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: trimAl

      - name: Fetch views data
        run: |
          views_file="$GITHUB_WORKSPACE/traffic/views.json"
          github_api_url="https://api.github.com/repos/${{ github.repository }}/traffic/views"
          github_token="${{ secrets.TRAFFIC_API }}"

          traffic_content=$(curl --request GET \
                             --url "$github_api_url" \
                             --header "X-GitHub-Api-Version:2022-11-28" \
                             --header "authorization: Bearer $github_token" \
                             --header 'content-type: application/json')

          echo "$traffic_content" > traffic_response.json
          jq '.views |= map({dailyUniques: .uniques, date: (.timestamp | split("T")[0]), count}) | del(.uniques) | .count = (.views | map(.count) | add)' traffic_response.json > temp_traffic.json && rm traffic_response.json
          cat temp_traffic.json
          jq --slurp '.[0].views as $existing | .[1].views as $new | .[0] | .views = ((($existing + $new) | group_by(.date) | map(.[0])) // []) | .count = (.views | map(.count) | add)' "$views_file" temp_traffic.json > temp_views.json
          cat temp_views.json > "$views_file" && rm temp_views.json temp_traffic.json
          cat "$views_file"