name: Traffic workflow test

on: workflow_dispatch

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: schedule-traffic-workflow

      - name: Fetch clones data
        run: |
          clones_file="$GITHUB_WORKSPACE/traffic/clones.json"
          github_api_url="https://api.github.com/repos/${{ github.repository }}/traffic/clones"
          github_token="${{ secrets.TRAFFIC_API }}"

          traffic_content=$(curl --request GET \
                             --url "$github_api_url" \
                             --header "X-GitHub-Api-Version:2022-11-28" \
                             --header "authorization: Bearer $github_token" \
                             --header 'content-type: application/json')

          echo "$traffic_content" > traffic_response.json
          jq '.clones |= map({dailyUniques: .uniques, date: (.timestamp | split("T")[0]), count}) | del(.uniques) | .count = (.clones | map(.count) | add)' traffic_response.json > temp_traffic.json && rm traffic_response.json
          cat temp_traffic.json
          
          jq --slurp '.[0].clones as $existing | .[1].clones as $new | .[0] | .clones = ((($existing + $new) | group_by(.date) | map(.[0])) // []) | .count = (.clones | map(.count) | add)' "$clones_file" temp_traffic.json > temp_clones.json

          cat temp_clones.json
          cat temp_clones.json > "$clones_file" && rm temp_clones.json temp_traffic.json
          cat "$clones_file"
