name: Traffic
on: workflow_dispatch

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch views data
        run: |
          curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/traffic/views \
              --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
              --header 'content-type: application/json' >> $GITHUB_WORKSPACE/traffic/views.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Updated traffic views $(date +'%d-%m-%Y')"
          branch: create-pull-request/patch-constraints
          delete-branch: true
          commit-message: "Update traffic views data"
