name: Traffic
on: workflow_dispatch

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      metadata: read
    steps:
      - name: Fetch traffic data
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/traffic/views \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
