name: Traffic workflow

on: workflow_dispatch

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { ref: schedule-traffic-workflow }
      - name: Set Date
        id: set_date
        run: echo "date=$(date +'%d-%m-%Y')" >> "$GITHUB_OUTPUT"
      - name: Fetch clones data
        run: |
          curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/traffic/clones \
              --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
              --header 'content-type: application/json' >> $GITHUB_WORKSPACE/traffic/clones.json
      - name: Fetch paths data
        run: |
          curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/traffic/popular/paths \
              --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
              --header 'content-type: application/json' >> $GITHUB_WORKSPACE/traffic/paths.json
      - name: Fetch referrers data
        run: |
          curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/traffic/popular/referrers \
              --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
              --header 'content-type: application/json' >> $GITHUB_WORKSPACE/traffic/referrers.json
      - name: Fetch views data
        run: |
          curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/traffic/views \
              --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
              --header 'content-type: application/json' >> $GITHUB_WORKSPACE/traffic/views.json
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions bot
          author_email: ${{ vars.CI_EMAIL }}
          message: Update traffic data
      - name: Create Pull Request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRAFFIC_API }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"title":"Update traffic data (${{ env.CURRENT_DATE }})","head":"schedule-traffic-workflow","base":"trimAl"}'

