name: Traffic workflow

on:
  schedule:
    - cron:  '57 6 7,17,27 * *'

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { ref: schedule-traffic-workflow }
      - name: Fetch clones data
        run: |
          clones_file="$GITHUB_WORKSPACE/traffic/clones.json"
          github_api_url="https://api.github.com/repos/${{ github.repository }}/traffic/clones"
          github_token="${{ secrets.TRAFFIC_API }}"

          traffic_content=$(curl --request GET \
                             --url "$github_api_url" \
                             --header "X-GitHub-Api-Version:2022-11-28" \
                             --header "authorization: Bearer $github_token" \
                             --header 'content-type: application/json')

          echo "$traffic_content" > traffic_response.json
          jq '.clones |= map({dailyUniques: .uniques, date: (.timestamp | split("T")[0]), count}) | del(.uniques) | .count = (.clones | map(.count) | add)' traffic_response.json > temp_traffic.json && rm traffic_response.json
          cat temp_traffic.json
          jq --slurp '.[0].clones as $existing | .[1].clones as $new | .[0] | .clones = ((($existing + $new) | group_by(.date) | map(.[0])) // []) | .count = (.clones | map(.count) | add)' "$clones_file" temp_traffic.json > temp_clones.json
          cat temp_clones.json > "$clones_file" && rm temp_clones.json temp_traffic.json
      - name: Fetch paths data
        run: |
          curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/traffic/popular/paths \
              --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
              --header 'content-type: application/json' >> $GITHUB_WORKSPACE/traffic/paths.json
      - name: Fetch referrers data
        run: |
          curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/traffic/popular/referrers \
              --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
              --header 'content-type: application/json' >> $GITHUB_WORKSPACE/traffic/referrers.json
      - name: Fetch views data
        run: |
          curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/traffic/views \
              --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
              --header 'content-type: application/json' >> $GITHUB_WORKSPACE/traffic/views.json
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions bot
          author_email: ${{ vars.CI_EMAIL }}
          message: Update traffic data
      - name: Create Pull Request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRAFFIC_API }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"title":"Update traffic data","head":"schedule-traffic-workflow","base":"trimAl"}'

