name: Traffic
on: workflow_dispatch

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch views data
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/traffic/views \
          --header 'authorization: Bearer ${{ secrets.TRAFFIC_API }}' \
          --header 'content-type: application/json' >> traffic/views.json
