name: Trigger traffic workflow

on: workflow_dispatch

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Log workflow triggering
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRAFFIC_API }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yml/dispatches \
            -d '{"ref":"schedule-traffic-workflow"}'
